package chat.stoat.ui.theme

import androidx.compose.ui.graphics.Color

object Colour {
    // Single accent: Terracotta (~#D97757 / #C6613F)
    val Seed = Color(0xFFD97757)
    val Terracotta = Color(0xFFD97757)
    val TerracottaDark = Color(0xFFC6613F)
    val TerracottaLight = Color(0xFFE28466)

    // Warm neutral palette - Light
    // Off-white background (~#FAF9F5), near-black warm text (#1F1E1D), hairline borders (~#E8E6DC)
    val PrimaryLight = Color(0xFFC6613F)
    val OnPrimaryLight = Color(0xFFFFFFFF)
    val PrimaryContainerLight = Color(0xFFF7E6DF)
    val OnPrimaryContainerLight = Color(0xFF5A2210)
    val InversePrimaryLight = Color(0xFFF09A7D)
    val SecondaryLight = Color(0xFF706D67)
    val OnSecondaryLight = Color(0xFFFFFFFF)
    val SecondaryContainerLight = Color(0xFFEDE9E3)
    val OnSecondaryContainerLight = Color(0xFF282622)
    val TertiaryLight = Color(0xFF86725B)
    val OnTertiaryLight = Color(0xFFFFFFFF)
    val TertiaryContainerLight = Color(0xFFF3ECE4)
    val OnTertiaryContainerLight = Color(0xFF322718)
    val BackgroundLight = Color(0xFFFAF9F5)
    val OnBackgroundLight = Color(0xFF1F1E1D)
    val SurfaceLight = Color(0xFFFAF9F5)
    val OnSurfaceLight = Color(0xFF1F1E1D)
    val SurfaceVariantLight = Color(0xFFEDEAE2)
    val OnSurfaceVariantLight = Color(0xFF5C5A55)
    val SurfaceTintLight = Color(0xFFC6613F)
    val InverseSurfaceLight = Color(0xFF2E2C29)
    val InverseOnSurfaceLight = Color(0xFFFAF9F5)
    val ErrorLight = Color(0xFFB3261E)
    val OnErrorLight = Color(0xFFFFFFFF)
    val ErrorContainerLight = Color(0xFFF9DEDC)
    val OnErrorContainerLight = Color(0xFF410E0B)
    val OutlineLight = Color(0xFFD8D5CC)
    val OutlineVariantLight = Color(0xFFE8E6DC) // Hairline border
    val ScrimLight = Color(0xFF000000)
    val SurfaceBrightLight = Color(0xFFFAF9F5)
    val SurfaceContainerLight = Color(0xFFF3F1EC)
    val SurfaceContainerHighLight = Color(0xFFEDEBE5)
    val SurfaceContainerHighestLight = Color(0xFFE7E5DF)
    val SurfaceContainerLowLight = Color(0xFFF7F6F1)
    val SurfaceContainerLowestLight = Color(0xFFFFFFFF)
    val SurfaceDimLight = Color(0xFFE4E2DC)
    val ShadowLight = Color(0x0A000000)
    val ControlActivatedLight = Color(0xFFF7E6DF)
    val ControlNormalLight = Color(0xFF706D67)
    val ControlHighlightLight = Color(0x0D000000)
    val TextPrimaryInverseLight = Color(0xFFFAF9F5)
    val TextSecondaryAndTertiaryInverseLight = Color(0xFFD8D5CC)
    val TextPrimaryInverseDisableOnlyLight = Color(0xFFFAF9F5)
    val TextSecondaryAndTertiaryInverseDisabledLight = Color(0xFFFAF9F5)
    val TextHintInverseLight = Color(0xFFFAF9F5)

    // Warm neutral palette - Dark
    // Warm charcoal background (~#1F1E1D / #262624), soft off-white text (#EDECE8), hairline borders (~#3A3834)
    val PrimaryDark = Color(0xFFE28466)
    val OnPrimaryDark = Color(0xFF2C1006)
    val PrimaryContainerDark = Color(0xFF5A2210)
    val OnPrimaryContainerDark = Color(0xFFF7E6DF)
    val InversePrimaryDark = Color(0xFFC6613F)
    val SecondaryDark = Color(0xFFCBC6BF)
    val OnSecondaryDark = Color(0xFF2A2824)
    val SecondaryContainerDark = Color(0xFF42403B)
    val OnSecondaryContainerDark = Color(0xFFEDE9E3)
    val TertiaryDark = Color(0xFFDDD0C2)
    val OnTertiaryDark = Color(0xFF33291B)
    val TertiaryContainerDark = Color(0xFF4D4030)
    val OnTertiaryContainerDark = Color(0xFFF3ECE4)
    val BackgroundDark = Color(0xFF1F1E1D)
    val OnBackgroundDark = Color(0xFFEDECE8)
    val SurfaceDark = Color(0xFF1F1E1D)
    val OnSurfaceDark = Color(0xFFEDECE8)
    val SurfaceVariantDark = Color(0xFF2E2C29)
    val OnSurfaceVariantDark = Color(0xFFAFAAA2)
    val SurfaceTintDark = Color(0xFFE28466)
    val InverseSurfaceDark = Color(0xFFEDECE8)
    val InverseOnSurfaceDark = Color(0xFF1F1E1D)
    val ErrorDark = Color(0xFFF2B8B5)
    val OnErrorDark = Color(0xFF601410)
    val ErrorContainerDark = Color(0xFF8C1D18)
    val OnErrorContainerDark = Color(0xFFF9DEDC)
    val OutlineDark = Color(0xFF63605A)
    val OutlineVariantDark = Color(0xFF3A3834) // Hairline border dark
    val ScrimDark = Color(0xFF000000)
    val SurfaceBrightDark = Color(0xFF363431)
    val SurfaceContainerDark = Color(0xFF262523)
    val SurfaceContainerHighDark = Color(0xFF2C2A28)
    val SurfaceContainerHighestDark = Color(0xFF343230)
    val SurfaceContainerLowDark = Color(0xFF22211F)
    val SurfaceContainerLowestDark = Color(0xFF191817)
    val SurfaceDimDark = Color(0xFF1A1918)
    val ShadowDark = Color(0xFF000000)
    val ControlActivatedDark = Color(0xFF5A2210)
    val ControlNormalDark = Color(0xFFAFAAA2)
    val ControlHighlightDark = Color(0x1AFFFFFF)
    val TextPrimaryInverseDark = Color(0xFF1F1E1D)
    val TextSecondaryAndTertiaryInverseDark = Color(0xFF5C5A55)
    val TextPrimaryInverseDisableOnlyDark = Color(0xFF1F1E1D)
    val TextSecondaryAndTertiaryInverseDisabledDark = Color(0xFF1F1E1D)
    val TextHintInverseDark = Color(0xFF1F1E1D)

    val PrimaryFixed = Color(0xFFF7E6DF)
    val PrimaryFixedDim = Color(0xFFE28466)
    val OnPrimaryFixed = Color(0xFF3D1204)
    val OnPrimaryFixedVariant = Color(0xFF5A2210)
    val SecondaryFixed = Color(0xFFEDE9E3)
    val SecondaryFixedDim = Color(0xFFCBC6BF)
    val OnSecondaryFixed = Color(0xFF1F1D19)
    val OnSecondaryFixedVariant = Color(0xFF42403B)
    val TertiaryFixed = Color(0xFFF3ECE4)
    val TertiaryFixedDim = Color(0xFFDDD0C2)
    val OnTertiaryFixed = Color(0xFF241C10)
    val OnTertiaryFixedVariant = Color(0xFF4D4030)
    val PrimaryPaletteKeyColor = Color(0xFFD97757)
    val SecondaryPaletteKeyColor = Color(0xFF706D67)
    val TertiaryPaletteKeyColor = Color(0xFF86725B)
    val NeutralPaletteKeyColor = Color(0xFF74716B)
    val NeutralVariantPaletteKeyColor = Color(0xFF76736C)
    val ErrorPaletteKeyColor = Color(0xFFDE3730)
}